#ifndef GAMEIO_CONFIG_H
#define GAMEIO_CONFIG_H

#include <QtCore/qglobal.h>

#define GAMEIO_VERSION_MAJOR 2
#define GAMEIO_VERSION_MINOR 0
#define GAMEIO_VERSION_PATCH 0
#define GAMEIO_VERSION_STR   "2.0.0"
#define GAMEIO_VERSION       GAMEIO_VERSION_CHECK(GAMEIO_VERSION_MAJOR, GAMEIO_VERSION_MINOR, GAMEIO_VERSION_PATCH)
#define GAMEIO_VERSION_CHECK QT_VERSION_CHECK

#endif // GAMEIO_CONFIG_H
